# File: build-windows.yml
# Path: /home/herb/Desktop/AndyLibrary/.github/workflows/build-windows.yml
# Standard: AIDEV-PascalCase-2.1
# Created: 2025-08-01
# Last Modified: 2025-08-01 10:49PM

name: Build Windows Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller fastapi uvicorn[standard] requests aiofiles
        pip install google-auth google-auth-oauthlib google-auth-httplib2
        pip install googleapiclient cryptography pydantic starlette psutil
        
    - name: Create PyInstaller spec file
      run: |
        echo "Creating PyInstaller spec file..."
        $specContent = @"
# -*- mode: python ; coding: utf-8 -*-
import os
from pathlib import Path

base_dir = Path('.')

a = Analysis(
    ['StartAndyGoogle.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('WebPages', 'WebPages'),
        ('Source', 'Source'),
        ('Config', 'Config'),
        ('Data', 'Data'),
        ('Public', 'Public'),
    ],
    hiddenimports=[
        'uvicorn.protocols.websockets.auto',
        'uvicorn.protocols.http.auto',
        'fastapi.routing',
        'fastapi.responses',
        'fastapi.staticfiles',
        'fastapi.middleware.cors',
        'uvicorn.main',
        'uvicorn.server',
        'uvicorn.config',
        'sqlite3',
        'json',
        'pathlib',
        'datetime',
        'socket',
        'threading',
        'webbrowser',
        'platform',
        'requests',
        'pydantic',
        'cryptography',
        'psutil',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='AndyLibrary',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
"@
        $specContent | Out-File -FilePath "andylibrary.spec" -Encoding UTF8
        
    - name: Build executable with spec file
      run: |
        echo "Building executable..."
        pyinstaller --clean andylibrary.spec
        
    - name: Verify executable
      run: |
        if (Test-Path "dist\AndyLibrary.exe") {
          Write-Host "✅ AndyLibrary.exe created successfully"
          $size = (Get-Item "dist\AndyLibrary.exe").Length
          Write-Host "📊 Size: $([math]::Round($size/1MB, 2)) MB"
        } else {
          Write-Host "❌ Build failed"
          exit 1
        }
        
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: AndyLibrary-Windows
        path: dist/AndyLibrary.exe
        retention-days: 30