# File: correct-windows-exe.yml
# Path: .github/workflows/correct-windows-exe.yml
# Standard: AIDEV-PascalCase-2.1
# Created: 2025-07-31
# Last Modified: 2025-07-31 04:05PM

name: Build CORRECT Windows Executable - Downloads Database

on:
  workflow_dispatch:  # Manual trigger only
  push:
    branches: [ main ]
    paths: 
      - 'Standalone/WindowsStandaloneApp.py'
      - '.github/workflows/correct-windows-exe.yml'

jobs:
  build-correct-windows-exe:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd Standalone
        pip install fastapi uvicorn requests pyinstaller
        
    - name: Verify files exist
      run: |
        echo "Checking for required files..."
        if (Test-Path "Standalone/WindowsStandaloneApp.py") {
          echo "✅ WindowsStandaloneApp.py found"
        } else {
          echo "❌ WindowsStandaloneApp.py missing"
          exit 1
        }
        if (Test-Path "WebPages") {
          echo "✅ WebPages directory found"
        } else {
          echo "❌ WebPages directory missing"
          exit 1
        }
        
    - name: Build Windows executable
      run: |
        cd Standalone
        echo "Building Windows executable..."
        pyinstaller --onefile --name="AndyLibrary-WindowsStandalone" --add-data="../WebPages;WebPages" --console WindowsStandaloneApp.py
        
    - name: Verify executable was created
      run: |
        echo "Checking if executable was created..."
        if (Test-Path "Standalone/dist/AndyLibrary-WindowsStandalone.exe") {
          $size = (Get-Item "Standalone/dist/AndyLibrary-WindowsStandalone.exe").Length / 1MB
          echo "✅ Executable created: $($size.ToString('F1')) MB"
        } else {
          echo "❌ Executable not found"
          exit 1
        }
        
    - name: Create README
      run: |
        echo "Creating README file..."
        echo "ANDY'S EDUCATIONAL LIBRARY - WINDOWS STANDALONE" > Standalone/dist/README.txt
        echo "Double-click AndyLibrary-WindowsStandalone.exe to run" >> Standalone/dist/README.txt
        
    - name: Create batch launcher
      run: |
        echo "Creating batch launcher..."
        echo "@echo off" > Standalone/dist/Start-AndyLibrary.bat
        echo "AndyLibrary-WindowsStandalone.exe" >> Standalone/dist/Start-AndyLibrary.bat
        echo "pause" >> Standalone/dist/Start-AndyLibrary.bat
        
        
    - name: Create package
      run: |
        cd Standalone/dist
        echo "Creating package..."
        Compress-Archive -Path * -DestinationPath "../AndyLibrary-Windows.zip" -Force
        
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: AndyLibrary-Windows-Standalone
        path: |
          Standalone/dist/AndyLibrary-WindowsStandalone.exe
          Standalone/dist/Start-AndyLibrary.bat
          Standalone/dist/README.txt
        retention-days: 90
        
    - name: Upload complete package
      uses: actions/upload-artifact@v4
      with:
        name: AndyLibrary-Windows-Package
        path: Standalone/AndyLibrary-Windows.zip
        retention-days: 90
        
    - name: Build summary
      run: |
        echo "✅ Windows executable build complete!"
        echo "Executable: AndyLibrary-WindowsStandalone.exe"
        echo "Package: AndyLibrary-Windows.zip"