# File: simple-windows-build.yml
# Path: /home/herb/Desktop/AndyLibrary/.github/workflows/simple-windows-build.yml
# Standard: AIDEV-PascalCase-2.1
# Created: 2025-07-26
# Last Modified: 2025-07-26 06:35PM

name: Simple Windows EXE Build

on:
  workflow_dispatch:  # Manual trigger only
  push:
    paths:
      - 'Standalone/**'

jobs:
  build-windows-exe:
    name: Build Windows Executable
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install PyInstaller and dependencies
      working-directory: ./Standalone
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install fastapi uvicorn aiofiles
        
    - name: Verify files exist
      working-directory: ./Standalone
      run: |
        echo "Checking Standalone directory contents:"
        dir
        echo "Checking if StandaloneAndyLibrary.py exists:"
        if exist StandaloneAndyLibrary.py (echo "✅ Main script found") else (echo "❌ Main script missing")
        
    - name: Build executable with PyInstaller
      working-directory: ./Standalone
      run: |
        echo "Building Windows executable..."
        pyinstaller --onefile --console --name "AndyLibrary-Standalone" StandaloneAndyLibrary.py
        
    - name: Verify build output
      working-directory: ./Standalone
      run: |
        echo "Checking dist directory:"
        dir dist
        if exist "dist\AndyLibrary-Standalone.exe" (echo "✅ EXE created successfully") else (echo "❌ EXE not found")
        
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: AndyLibrary-Windows-EXE
        path: Standalone/dist/AndyLibrary-Standalone.exe
        retention-days: 30